version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - mynetwork

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local
